version: '3'
services:

  caddy:
    image: caddy:2.1.1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      XDG_DATA_HOME: /mount/server/data
      XDG_CONFIG_HOME: /mount/server/config
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_VOLUME:-caddy_data}:/mount/server

  postgres:
    image: "postgis/postgis:13-3.0-alpine" 
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_LOGIN}"
      POSTGRES_DB: Wecity
    ports:
      - '5432:5432'
    volumes:
      - ${PG_VOLUME:-pg_data}:/var/lib/postgresql/data
      - ./postgres:/scripts

  hasura:
    image: hasura/graphql-engine:v2.1.0-beta.2
    ports:
    - "8080"
    depends_on:
      - postgres
      - hasura-backend-plus
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "host=postgres dbname=Wecity port=5432 user=${DB_LOGIN} password=${DB_PASSWORD}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "key": "$JWT_SECRET"}'
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: 'true'

  hasura-backend-plus:
    image: nhost/hasura-backend-plus:2.7.1
    ports:
      - '4000'
    restart: always
    volumes:
      - ./mail-templates:/app/custom/emails
      - ./storage-rules:/app/custom/storage-rules
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      MAGIC_LINK_ENABLED: "true"
      DATABASE_URL: >-
        postgres://${DB_LOGIN}:${DB_PASSWORD}@postgres:5432/Wecity
      REGISTRATION_CUSTOM_FIELDS: "display_name"
      JWT_CUSTOM_FIELDS: display_name,avatar_url
      HIBP_ENABLED: "false"
      SERVER_URL: https://api.weee.city
      JWT_KEY: '$JWT_PRIVATE_KEY'
      JWT_ALGORITHM: RS256
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      S3_ENDPOINT: https://s3.eu-north-1.amazonaws.com
      S3_BUCKET: s3.weee.city
      S3_ACCESS_KEY_ID: AKIA2IYHTX7JSN5BFAEC
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      GOOGLE_ENABLED: 'true'
      GOOGLE_CLIENT_ID: '766690753861-u0muglqq0o81pu11cg1mnm3uh4grgprp.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      FACEBOOK_ENABLED: 'true'
      FACEBOOK_CLIENT_ID: '1075569679634321'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      AUTO_MIGRATE: 'true'
      COOKIE_SAME_SITE: 'none'
      COOKIE_SECURE: 'true'
      COOKIE_SECRET: '${COOKIE_SECRET}'
      VERIFY_EMAILS: 'true'
      EMAILS_ENABLED: 'true'
      SMTP_HOST: 'email-smtp.eu-west-1.amazonaws.com'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_USER: 'AKIA2IYHTX7JSRJLISNC'
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_SENDER: 'Wecity Platform <hi@weee.city>'
      NOTIFY_EMAIL_CHANGE: 'true'
      AUTO_ACTIVATE_NEW_USERS: 'false'
      REDIRECT_URL_SUCCESS: 'https://weee.city/success'
      REDIRECT_URL_ERROR: 'https://weee.city/failure'
      MIN_PASSWORD_LENGTH: 6
      DEFAULT_ALLOWED_USER_ROLES: user,me
      ALLOWED_USER_ROLES: user,me

  hasura-backend-plus-dev:
    image: nhost/hasura-backend-plus:2.7.1
    ports:
      - '4000'
    restart: always
    volumes:
      - ./mail-templates:/app/custom/emails
      - ./storage-rules:/app/custom/storage-rules
    depends_on:
      - hasura-backend-plus
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      MAGIC_LINK_ENABLED: "true"
      DATABASE_URL: >-
        postgres://${DB_LOGIN}:${DB_PASSWORD}@postgres:5432/Wecity
      REGISTRATION_CUSTOM_FIELDS: "display_name"
      JWT_CUSTOM_FIELDS: display_name,avatar_url
      HIBP_ENABLED: "false"
      SERVER_URL: https://api-dev.weee.city
      JWT_KEY: '$JWT_PRIVATE_KEY'
      JWT_ALGORITHM: RS256
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      S3_ENDPOINT: https://s3.eu-north-1.amazonaws.com
      S3_BUCKET: s3.weee.city
      S3_ACCESS_KEY_ID: AKIA2IYHTX7JSN5BFAEC
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      GOOGLE_ENABLED: 'true'
      GOOGLE_CLIENT_ID: '766690753861-u0muglqq0o81pu11cg1mnm3uh4grgprp.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      FACEBOOK_ENABLED: 'true'
      FACEBOOK_CLIENT_ID: '1075569679634321'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      AUTO_MIGRATE: 'true'
      COOKIE_SAME_SITE: 'none'
      COOKIE_SECURE: 'true'
      COOKIE_SECRET: '${COOKIE_SECRET}'
      VERIFY_EMAILS: 'true'
      EMAILS_ENABLED: 'true'
      SMTP_HOST: 'email-smtp.eu-west-1.amazonaws.com'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_USER: 'AKIA2IYHTX7JSRJLISNC'
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_SENDER: 'Wecity Platform <hi@weee.city>'
      NOTIFY_EMAIL_CHANGE: 'true'
      AUTO_ACTIVATE_NEW_USERS: 'false'
      REDIRECT_URL_SUCCESS: 'http://dev.weee.city/success'
      REDIRECT_URL_ERROR: 'http://dev.weee.city/failure'
      MIN_PASSWORD_LENGTH: 6
      DEFAULT_ALLOWED_USER_ROLES: user,me
      ALLOWED_USER_ROLES: user,me

  hasura-backend-plus-local:
    image: nhost/hasura-backend-plus:2.7.1
    ports:
      - '4000'
    restart: always
    depends_on:
      - hasura-backend-plus
    volumes:
      - ./mail-templates:/app/custom/emails
      - ./storage-rules:/app/custom/storage-rules
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      MAGIC_LINK_ENABLED: "true"
      DATABASE_URL: >-
        postgres://${DB_LOGIN}:${DB_PASSWORD}@postgres:5432/Wecity
      REGISTRATION_CUSTOM_FIELDS: "display_name"
      JWT_CUSTOM_FIELDS: display_name,avatar_url
      HIBP_ENABLED: "false"
      SERVER_URL: https://api-local.weee.city
      JWT_KEY: '$JWT_PRIVATE_KEY'
      JWT_ALGORITHM: RS256
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      S3_ENDPOINT: https://s3.eu-north-1.amazonaws.com
      S3_BUCKET: s3.weee.city
      S3_ACCESS_KEY_ID: AKIA2IYHTX7JSN5BFAEC
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      GOOGLE_ENABLED: 'true'
      GOOGLE_CLIENT_ID: '766690753861-u0muglqq0o81pu11cg1mnm3uh4grgprp.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      FACEBOOK_ENABLED: 'true'
      FACEBOOK_CLIENT_ID: '1075569679634321'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      AUTO_MIGRATE: 'true'
      COOKIE_SAME_SITE: 'none'
      COOKIE_SECURE: 'true'
      COOKIE_SECRET: '${COOKIE_SECRET}'
      VERIFY_EMAILS: 'true'
      EMAILS_ENABLED: 'true'
      SMTP_HOST: 'email-smtp.eu-west-1.amazonaws.com'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_USER: 'AKIA2IYHTX7JSRJLISNC'
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_SENDER: 'Wecity Platform <hi@weee.city>'
      NOTIFY_EMAIL_CHANGE: 'true'
      AUTO_ACTIVATE_NEW_USERS: 'false'
      REDIRECT_URL_SUCCESS: 'http://localhost:3000/success'
      REDIRECT_URL_ERROR: 'http://localhost:3000/failure'
      MIN_PASSWORD_LENGTH: 6
      DEFAULT_ALLOWED_USER_ROLES: user,me
      ALLOWED_USER_ROLES: user,me

  wcty-admin:
    image: wcty/admin:latest
    restart: unless-stopped
    ports:
      - '4000'
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      COOKIE_SECRET: '${COOKIE_SECRET}'
      COOKIE_SECURE: 'true'
      COOKIE_SAME_SITE: 'none'
      SMTP_HOST: 'email-smtp.eu-west-1.amazonaws.com'
      SMTP_USER: 'AKIA2IYHTX7JSRJLISNC'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_SECURE: 'true'
      SMTP_SENDER: 'Wecity Platform <hi@weee.city>'
      SMTP_PORT: 465
      RECEIVER_ADDRESS: hi@weee.city
      REDIRECT_URL_SUCCESS: https://weee.city
      VAPID_PRIVATE: '${VAPID_PRIVATE}'
      VAPID_PUBLIC: '${VAPID_PUBLIC}'
      AUTH_KEY: '${AUTH_KEY}'

  martin:
    image: urbica/martin:latest
    restart: unless-stopped
    environment:
      WATCH_MODE: "true"
      DATABASE_URL: "host=postgres dbname=Wecity port=5432 user=${DB_LOGIN} password=${DB_PASSWORD}"
    ports:
      - '3000'
    depends_on:
      - postgres

volumes:
  caddy_data:
  pg_data: