image: node:12.13.0-alpine

cache:
  paths:
    - node_modules/

before_script:
  - npm i -g firebase-tools
  - npm install

dev-hosting:
  stage: deploy
  script:
    - CI=false npm run build-dev
    - firebase deploy --only hosting:dev-weee-city --token $FIREBASE_TOKEN
  only:
    - develop
  environment:
    name: production
    url: https://dev.weee.city

prod-hosting:
  stage: deploy
  script:
    - CI=false npm run build
    - firebase deploy --only hosting:wecity --token $FIREBASE_TOKEN
  only:
    - main
  environment:
    name: production
    url: https://weee.city