name: Deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps/fe/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      uses: hermanmitish/action-ssh@master
      env:
        DB_LOGIN: ${{ secrets.DB_LOGIN }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
        VAPID_PUBLIC: ${{ secrets.VAPID_PUBLIC }}
        AUTH_KEY: ${{ secrets.AUTH_KEY }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        CADDY_VOLUME: ${{ secrets.CADDY_VOLUME }}
        CERT_PASS: ${{ secrets.CERT_PASS }}
        HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
        PG_VOLUME: ${{ secrets.PG_VOLUME }}
        APPLE_CLIENT_ID: '${{ secrets.APPLE_CLIENT_ID }}'
        APPLE_TEAM_ID: '${{ secrets.APPLE_TEAM_ID }}'
        APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
        APPLE_PRIVATE_KEY: '${{ secrets.APPLE_PRIVATE_KEY }}'

      with:
        hosts: ${{ secrets.HOST }}
        privateKey: ${{ secrets.KEY }}
        command: |
          cd ~/wcty
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          git fetch --all
          git reset --hard origin/main
          yarn

          git diff --quiet main~1 main apps/be/Caddyfile
          if [ $? -ne 0 ]; 
          then 
            echo "Updated Caddyfile"
            yarn nx deploy-caddy be
          fi

          git diff --quiet main~1 main apps/be/mail-templates/* apps/be/storage-rules/*
          if [ $? -ne 0 ]; 
          then 
            echo "Updated HBP"
            yarn nx deploy-hbp be
          fi

          git diff --quiet main~1 main apps/be/postgres/*
          if [ $? -ne 0 ]; 
          then 
            echo "Updated postgres"
            yarn nx deploy-postgres be
          fi

          yarn nx affected --target=deploy --base=main~1 --head=main --parallel --exclude=fe
          yarn nx serve be
