name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Firebase CLI
      run: npm i -g firebase-tools
    - name: Install Packages
      run: npm install
    - name: Build page
      env:
        CI: false
      run: npm run build
    - name: Deploy to Firebase
      env:
        name: production
        url: https://weee.city
      run: firebase deploy --only hosting:wecity --token ${{ secrets.FIREBASE_TOKEN }}
